// Generated by Workman compiler
const Empty = Object.freeze({ tag: "Empty", type: "List" });
const Link = (arg0, arg1) => ({
  tag: "Link",
  type: "List",
  _0: arg0,
  _1: arg1
});
export { Empty, Link };
