// Generated by Workman compiler
import { Empty, Link } from "./list/core.mjs";
import { intAdd, intSub, intCompare } from "./core/int.mjs";
import { Ok, Err } from "./result/core.mjs";
import { LT, EQ, GT } from "./core/ordering.mjs";
import { Some, None } from "./option/core.mjs";
import { charEq, add, sub, mul, div, cmpInt, eq, neq, lt, gt, lte, gte, boolAnd, boolOr, not, print } from "./prelude.mjs";
import { wrapResultValue, callInfectious, recordGetInfectious } from "../runtime.mjs";
const listLength = (() => {
  const listLength = (list) => {
    return (() => {
      const __match_scrutinee = list;
      if (((__match_scrutinee)?.tag === "Empty") && ((__match_scrutinee)?.type === "List")) {
        return 0;
      }
      if (((__match_scrutinee)?.tag === "Link") && ((__match_scrutinee)?.type === "List")) {
        const rest = ((__match_scrutinee)._1);
        return (intAdd)(1, (listLength)(rest));
      }
      throw new Error("Non-exhaustive patterns at runtime");
    })();
  };
  return listLength;
})();
const listAppend = (() => {
  const listAppend = (xs, ys) => {
    return (() => {
      const __match_scrutinee_0 = [xs, ys];
      if ((Array.isArray((__match_scrutinee_0))) && ((__match_scrutinee_0).length === 2) && (((__match_scrutinee_0)[0])?.tag === "Empty") && (((__match_scrutinee_0)[0])?.type === "List")) {
        const ys = ((__match_scrutinee_0)[1]);
        return ys;
      }
      if ((Array.isArray((__match_scrutinee_0))) && ((__match_scrutinee_0).length === 2) && (((__match_scrutinee_0)[0])?.tag === "Link") && (((__match_scrutinee_0)[0])?.type === "List")) {
        const x = (((__match_scrutinee_0)[0])._0);
        const rest_1 = (((__match_scrutinee_0)[0])._1);
        const ys = ((__match_scrutinee_0)[1]);
        return ({ tag: "Link", type: "List",
          _0: x,
          _1: (listAppend)(rest_1, ys)
        });
      }
      throw new Error("Non-exhaustive patterns at runtime");
    })();
  };
  return listAppend;
})();
const listMap = (() => {
  const listMap = (f, list_2) => {
    return (() => {
      const __match_scrutinee_3 = [f, list_2];
      if ((Array.isArray((__match_scrutinee_3))) && ((__match_scrutinee_3).length === 2) && (((__match_scrutinee_3)[1])?.tag === "Empty") && (((__match_scrutinee_3)[1])?.type === "List")) {
        const f = ((__match_scrutinee_3)[0]);
        return ({ tag: "Empty", type: "List"});
      }
      if ((Array.isArray((__match_scrutinee_3))) && ((__match_scrutinee_3).length === 2) && (((__match_scrutinee_3)[1])?.tag === "Link") && (((__match_scrutinee_3)[1])?.type === "List")) {
        const f = ((__match_scrutinee_3)[0]);
        const x_4 = (((__match_scrutinee_3)[1])._0);
        const rest_5 = (((__match_scrutinee_3)[1])._1);
        return ({ tag: "Link", type: "List",
          _0: (f)(x_4),
          _1: (listMap)(f, rest_5)
        });
      }
      throw new Error("Non-exhaustive patterns at runtime");
    })();
  };
  return listMap;
})();
const listFilter = (() => {
  const listFilter = (predicate, list_6) => {
    return (() => {
      const __match_scrutinee_7 = [predicate, list_6];
      if ((Array.isArray((__match_scrutinee_7))) && ((__match_scrutinee_7).length === 2) && (((__match_scrutinee_7)[1])?.tag === "Empty") && (((__match_scrutinee_7)[1])?.type === "List")) {
        const predicate = ((__match_scrutinee_7)[0]);
        return ({ tag: "Empty", type: "List"});
      }
      if ((Array.isArray((__match_scrutinee_7))) && ((__match_scrutinee_7).length === 2) && (((__match_scrutinee_7)[1])?.tag === "Link") && (((__match_scrutinee_7)[1])?.type === "List")) {
        const predicate = ((__match_scrutinee_7)[0]);
        const x_8 = (((__match_scrutinee_7)[1])._0);
        const rest_9 = (((__match_scrutinee_7)[1])._1);
        return (() => {
          const __match_scrutinee_10 = (predicate)(x_8);
          if (((__match_scrutinee_10) === true)) {
            return ({ tag: "Link", type: "List",
              _0: x_8,
              _1: (listFilter)(predicate, rest_9)
            });
          }
          if (((__match_scrutinee_10) === false)) {
            return (listFilter)(predicate, rest_9);
          }
          throw new Error("Non-exhaustive patterns at runtime");
        })();
      }
      throw new Error("Non-exhaustive patterns at runtime");
    })();
  };
  return listFilter;
})();
const listTake = (() => {
  const listTake = (list_11, count) => {
    return (() => {
      const __match_scrutinee_12 = [list_11, count];
      if ((Array.isArray((__match_scrutinee_12))) && ((__match_scrutinee_12).length === 2) && (((__match_scrutinee_12)[0])?.tag === "Empty") && (((__match_scrutinee_12)[0])?.type === "List")) {
        return ({ tag: "Empty", type: "List"});
      }
      if ((Array.isArray((__match_scrutinee_12))) && ((__match_scrutinee_12).length === 2) && (((__match_scrutinee_12)[1]) === 0)) {
        return ({ tag: "Empty", type: "List"});
      }
      if ((Array.isArray((__match_scrutinee_12))) && ((__match_scrutinee_12).length === 2) && (((__match_scrutinee_12)[0])?.tag === "Link") && (((__match_scrutinee_12)[0])?.type === "List")) {
        const x_13 = (((__match_scrutinee_12)[0])._0);
        const rest_14 = (((__match_scrutinee_12)[0])._1);
        const count = ((__match_scrutinee_12)[1]);
        return ({ tag: "Link", type: "List",
          _0: x_13,
          _1: (listTake)(rest_14, (intSub)(count, 1))
        });
      }
      throw new Error("Non-exhaustive patterns at runtime");
    })();
  };
  return listTake;
})();
const listDrop = (() => {
  const listDrop = (list_15, count_16) => {
    return (() => {
      const __match_scrutinee_17 = [list_15, count_16];
      if ((Array.isArray((__match_scrutinee_17))) && ((__match_scrutinee_17).length === 2) && (((__match_scrutinee_17)[1]) === 0)) {
        const list_15 = ((__match_scrutinee_17)[0]);
        return list_15;
      }
      if ((Array.isArray((__match_scrutinee_17))) && ((__match_scrutinee_17).length === 2) && (((__match_scrutinee_17)[0])?.tag === "Empty") && (((__match_scrutinee_17)[0])?.type === "List")) {
        return ({ tag: "Empty", type: "List"});
      }
      if ((Array.isArray((__match_scrutinee_17))) && ((__match_scrutinee_17).length === 2) && (((__match_scrutinee_17)[0])?.tag === "Link") && (((__match_scrutinee_17)[0])?.type === "List")) {
        const rest_18 = (((__match_scrutinee_17)[0])._1);
        const count_16 = ((__match_scrutinee_17)[1]);
        return (listDrop)(rest_18, (intSub)(count_16, 1));
      }
      throw new Error("Non-exhaustive patterns at runtime");
    })();
  };
  return listDrop;
})();
const listSlice = (list_19, start, end) => {
  return (() => {
    const dropped = (listDrop)(list_19, start);
    return (listTake)(dropped, (intSub)(end, start));
  })();
};
const listAt = (() => {
  const listAt = (list_20, index, error) => {
    return (() => {
      const __match_scrutinee_21 = [list_20, index, error];
      if ((Array.isArray((__match_scrutinee_21))) && ((__match_scrutinee_21).length === 3) && (((__match_scrutinee_21)[0])?.tag === "Empty") && (((__match_scrutinee_21)[0])?.type === "List")) {
        const error = ((__match_scrutinee_21)[2]);
        return ({ tag: "Err", type: "Result",
          _0: error
        });
      }
      if ((Array.isArray((__match_scrutinee_21))) && ((__match_scrutinee_21).length === 3) && (((__match_scrutinee_21)[0])?.tag === "Link") && (((__match_scrutinee_21)[0])?.type === "List") && (((__match_scrutinee_21)[1]) === 0)) {
        const x_22 = (((__match_scrutinee_21)[0])._0);
        return wrapResultValue(x_22);
      }
      if ((Array.isArray((__match_scrutinee_21))) && ((__match_scrutinee_21).length === 3) && (((__match_scrutinee_21)[0])?.tag === "Link") && (((__match_scrutinee_21)[0])?.type === "List")) {
        const rest_23 = (((__match_scrutinee_21)[0])._1);
        const index = ((__match_scrutinee_21)[1]);
        const error = ((__match_scrutinee_21)[2]);
        return callInfectious(listAt, rest_23, (intSub)(index, 1), error);
      }
      throw new Error("Non-exhaustive patterns at runtime");
    })();
  };
  return listAt;
})();
const listFoldl = (() => {
  const listFoldl = (f_24, acc, list_25) => {
    return (() => {
      const __match_scrutinee_26 = [f_24, acc, list_25];
      if ((Array.isArray((__match_scrutinee_26))) && ((__match_scrutinee_26).length === 3) && (((__match_scrutinee_26)[2])?.tag === "Empty") && (((__match_scrutinee_26)[2])?.type === "List")) {
        const f_24 = ((__match_scrutinee_26)[0]);
        const acc = ((__match_scrutinee_26)[1]);
        return acc;
      }
      if ((Array.isArray((__match_scrutinee_26))) && ((__match_scrutinee_26).length === 3) && (((__match_scrutinee_26)[2])?.tag === "Link") && (((__match_scrutinee_26)[2])?.type === "List")) {
        const f_24 = ((__match_scrutinee_26)[0]);
        const acc = ((__match_scrutinee_26)[1]);
        const x_27 = (((__match_scrutinee_26)[2])._0);
        const rest_28 = (((__match_scrutinee_26)[2])._1);
        return (listFoldl)(f_24, (f_24)(acc, x_27), rest_28);
      }
      throw new Error("Non-exhaustive patterns at runtime");
    })();
  };
  return listFoldl;
})();
const listFoldr = (() => {
  const listFoldr = (f_29, acc_30, list_31) => {
    return (() => {
      const __match_scrutinee_32 = [f_29, acc_30, list_31];
      if ((Array.isArray((__match_scrutinee_32))) && ((__match_scrutinee_32).length === 3) && (((__match_scrutinee_32)[2])?.tag === "Empty") && (((__match_scrutinee_32)[2])?.type === "List")) {
        const f_29 = ((__match_scrutinee_32)[0]);
        const acc_30 = ((__match_scrutinee_32)[1]);
        return acc_30;
      }
      if ((Array.isArray((__match_scrutinee_32))) && ((__match_scrutinee_32).length === 3) && (((__match_scrutinee_32)[2])?.tag === "Link") && (((__match_scrutinee_32)[2])?.type === "List")) {
        const f_29 = ((__match_scrutinee_32)[0]);
        const acc_30 = ((__match_scrutinee_32)[1]);
        const x_33 = (((__match_scrutinee_32)[2])._0);
        const rest_34 = (((__match_scrutinee_32)[2])._1);
        return (f_29)(x_33, (listFoldr)(f_29, acc_30, rest_34));
      }
      throw new Error("Non-exhaustive patterns at runtime");
    })();
  };
  return listFoldr;
})();
const reverseAcc = (() => {
  const reverseAcc = (list_35, acc_36) => {
    return (() => {
      const __match_scrutinee_37 = [list_35, acc_36];
      if ((Array.isArray((__match_scrutinee_37))) && ((__match_scrutinee_37).length === 2) && (((__match_scrutinee_37)[0])?.tag === "Empty") && (((__match_scrutinee_37)[0])?.type === "List")) {
        const acc_36 = ((__match_scrutinee_37)[1]);
        return acc_36;
      }
      if ((Array.isArray((__match_scrutinee_37))) && ((__match_scrutinee_37).length === 2) && (((__match_scrutinee_37)[0])?.tag === "Link") && (((__match_scrutinee_37)[0])?.type === "List")) {
        const x_38 = (((__match_scrutinee_37)[0])._0);
        const rest_39 = (((__match_scrutinee_37)[0])._1);
        const acc_36 = ((__match_scrutinee_37)[1]);
        return (reverseAcc)(rest_39, ({ tag: "Link", type: "List",
          _0: x_38,
          _1: acc_36
        }));
      }
      throw new Error("Non-exhaustive patterns at runtime");
    })();
  };
  return reverseAcc;
})();
const listReverse = (list_40) => (reverseAcc)(list_40, ({ tag: "Empty", type: "List"}));
const listRange = (() => {
  const listRange = (start_41, finish) => {
    return (() => {
      const __match_scrutinee_42 = [start_41, finish];
      if ((Array.isArray((__match_scrutinee_42))) && ((__match_scrutinee_42).length === 2)) {
        const start_41 = ((__match_scrutinee_42)[0]);
        const finish = ((__match_scrutinee_42)[1]);
        return (() => {
          const __match_scrutinee_43 = (intCompare)(start_41, finish);
          if (((__match_scrutinee_43)?.tag === "GT") && ((__match_scrutinee_43)?.type === "Ordering")) {
            return ({ tag: "Empty", type: "List"});
          }
          if (true) {
            return ({ tag: "Link", type: "List",
              _0: start_41,
              _1: (listRange)((intAdd)(start_41, 1), finish)
            });
          }
          throw new Error("Non-exhaustive patterns at runtime");
        })();
      }
      throw new Error("Non-exhaustive patterns at runtime");
    })();
  };
  return listRange;
})();
const listInsertBy = (() => {
  const listInsertBy = (cmp, value, list_44) => {
    return (() => {
      const __match_scrutinee_45 = [cmp, value, list_44];
      if ((Array.isArray((__match_scrutinee_45))) && ((__match_scrutinee_45).length === 3)) {
        const cmp = ((__match_scrutinee_45)[0]);
        const value = ((__match_scrutinee_45)[1]);
        const list_44 = ((__match_scrutinee_45)[2]);
        return (() => {
          const __match_scrutinee_46 = list_44;
          if (((__match_scrutinee_46)?.tag === "Empty") && ((__match_scrutinee_46)?.type === "List")) {
            return ({ tag: "Link", type: "List",
              _0: value,
              _1: ({ tag: "Empty", type: "List"})
            });
          }
          if (((__match_scrutinee_46)?.tag === "Link") && ((__match_scrutinee_46)?.type === "List")) {
            const x_47 = ((__match_scrutinee_46)._0);
            const rest_48 = ((__match_scrutinee_46)._1);
            return (() => {
              const __match_scrutinee_49 = (cmp)(value, x_47);
              if (((__match_scrutinee_49)?.tag === "GT") && ((__match_scrutinee_49)?.type === "Ordering")) {
                return ({ tag: "Link", type: "List",
                  _0: x_47,
                  _1: (listInsertBy)(cmp, value, rest_48)
                });
              }
              if (true) {
                return ({ tag: "Link", type: "List",
                  _0: value,
                  _1: ({ tag: "Link", type: "List",
                  _0: x_47,
                  _1: rest_48
                })
                });
              }
              throw new Error("Non-exhaustive patterns at runtime");
            })();
          }
          throw new Error("Non-exhaustive patterns at runtime");
        })();
      }
      throw new Error("Non-exhaustive patterns at runtime");
    })();
  };
  return listInsertBy;
})();
const listInsertionSortBy = (() => {
  const listInsertionSortBy = (cmp_50, list_51) => {
    return (() => {
      const __match_scrutinee_52 = [cmp_50, list_51];
      if ((Array.isArray((__match_scrutinee_52))) && ((__match_scrutinee_52).length === 2)) {
        const cmp_50 = ((__match_scrutinee_52)[0]);
        const list_51 = ((__match_scrutinee_52)[1]);
        return (() => {
          const __match_scrutinee_53 = list_51;
          if (((__match_scrutinee_53)?.tag === "Empty") && ((__match_scrutinee_53)?.type === "List")) {
            return ({ tag: "Empty", type: "List"});
          }
          if (((__match_scrutinee_53)?.tag === "Link") && ((__match_scrutinee_53)?.type === "List")) {
            const x_54 = ((__match_scrutinee_53)._0);
            const rest_55 = ((__match_scrutinee_53)._1);
            return (listInsertBy)(cmp_50, x_54, (listInsertionSortBy)(cmp_50, rest_55));
          }
          throw new Error("Non-exhaustive patterns at runtime");
        })();
      }
      throw new Error("Non-exhaustive patterns at runtime");
    })();
  };
  return listInsertionSortBy;
})();
const listSortInt = (list_56) => (listInsertionSortBy)(intCompare, list_56);
const listJoin = (() => {
  const listJoin = (sep, list_57) => {
    return (() => {
      const __match_scrutinee_58 = [sep, list_57];
      if ((Array.isArray((__match_scrutinee_58))) && ((__match_scrutinee_58).length === 2) && (((__match_scrutinee_58)[1])?.tag === "Empty") && (((__match_scrutinee_58)[1])?.type === "List")) {
        const sep = ((__match_scrutinee_58)[0]);
        return ({ tag: "Empty", type: "List"});
      }
      if ((Array.isArray((__match_scrutinee_58))) && ((__match_scrutinee_58).length === 2) && (((__match_scrutinee_58)[1])?.tag === "Link") && (((__match_scrutinee_58)[1])?.type === "List") && ((((__match_scrutinee_58)[1])._1)?.tag === "Empty") && ((((__match_scrutinee_58)[1])._1)?.type === "List")) {
        const sep = ((__match_scrutinee_58)[0]);
        const x_59 = (((__match_scrutinee_58)[1])._0);
        return x_59;
      }
      if ((Array.isArray((__match_scrutinee_58))) && ((__match_scrutinee_58).length === 2) && (((__match_scrutinee_58)[1])?.tag === "Link") && (((__match_scrutinee_58)[1])?.type === "List")) {
        const sep = ((__match_scrutinee_58)[0]);
        const x_60 = (((__match_scrutinee_58)[1])._0);
        const rest_61 = (((__match_scrutinee_58)[1])._1);
        return (listAppend)(x_60, (listAppend)(sep, (listJoin)(sep, rest_61)));
      }
      throw new Error("Non-exhaustive patterns at runtime");
    })();
  };
  return listJoin;
})();
const listForEach = (() => {
  const listForEach = (f_62, list_63) => {
    return (() => {
      const __match_scrutinee_64 = [f_62, list_63];
      if ((Array.isArray((__match_scrutinee_64))) && ((__match_scrutinee_64).length === 2) && (((__match_scrutinee_64)[1])?.tag === "Empty") && (((__match_scrutinee_64)[1])?.type === "List")) {
        const f_62 = ((__match_scrutinee_64)[0]);
        return undefined;
      }
      if ((Array.isArray((__match_scrutinee_64))) && ((__match_scrutinee_64).length === 2) && (((__match_scrutinee_64)[1])?.tag === "Link") && (((__match_scrutinee_64)[1])?.type === "List")) {
        const f_62 = ((__match_scrutinee_64)[0]);
        const x_65 = (((__match_scrutinee_64)[1])._0);
        const rest_66 = (((__match_scrutinee_64)[1])._1);
        return (() => {
          const result = (f_62)(x_65);
          return (listForEach)(f_62, rest_66);
        })();
      }
      throw new Error("Non-exhaustive patterns at runtime");
    })();
  };
  return listForEach;
})();
const listFlatMap = (() => {
  const listFlatMap = (f_67, list_68) => {
    return (() => {
      const __match_scrutinee_69 = [f_67, list_68];
      if ((Array.isArray((__match_scrutinee_69))) && ((__match_scrutinee_69).length === 2) && (((__match_scrutinee_69)[1])?.tag === "Empty") && (((__match_scrutinee_69)[1])?.type === "List")) {
        const f_67 = ((__match_scrutinee_69)[0]);
        return ({ tag: "Empty", type: "List"});
      }
      if ((Array.isArray((__match_scrutinee_69))) && ((__match_scrutinee_69).length === 2) && (((__match_scrutinee_69)[1])?.tag === "Link") && (((__match_scrutinee_69)[1])?.type === "List")) {
        const f_67 = ((__match_scrutinee_69)[0]);
        const x_70 = (((__match_scrutinee_69)[1])._0);
        const rest_71 = (((__match_scrutinee_69)[1])._1);
        return (listAppend)((f_67)(x_70), (listFlatMap)(f_67, rest_71));
      }
      throw new Error("Non-exhaustive patterns at runtime");
    })();
  };
  return listFlatMap;
})();
const listFind = (() => {
  const listFind = (predicate_72, list_73) => {
    return (() => {
      const __match_scrutinee_74 = [predicate_72, list_73];
      if ((Array.isArray((__match_scrutinee_74))) && ((__match_scrutinee_74).length === 2) && (((__match_scrutinee_74)[1])?.tag === "Empty") && (((__match_scrutinee_74)[1])?.type === "List")) {
        const predicate_72 = ((__match_scrutinee_74)[0]);
        return ({ tag: "None", type: "Option"});
      }
      if ((Array.isArray((__match_scrutinee_74))) && ((__match_scrutinee_74).length === 2) && (((__match_scrutinee_74)[1])?.tag === "Link") && (((__match_scrutinee_74)[1])?.type === "List")) {
        const predicate_72 = ((__match_scrutinee_74)[0]);
        const x_75 = (((__match_scrutinee_74)[1])._0);
        const rest_76 = (((__match_scrutinee_74)[1])._1);
        return (() => {
          const __match_scrutinee_77 = (predicate_72)(x_75);
          if (((__match_scrutinee_77) === true)) {
            return ({ tag: "Some", type: "Option",
              _0: x_75
            });
          }
          if (((__match_scrutinee_77) === false)) {
            return (listFind)(predicate_72, rest_76);
          }
          throw new Error("Non-exhaustive patterns at runtime");
        })();
      }
      throw new Error("Non-exhaustive patterns at runtime");
    })();
  };
  return listFind;
})();
const listAny = (() => {
  const listAny = (predicate_78, list_79) => {
    return (() => {
      const __match_scrutinee_80 = [predicate_78, list_79];
      if ((Array.isArray((__match_scrutinee_80))) && ((__match_scrutinee_80).length === 2) && (((__match_scrutinee_80)[1])?.tag === "Empty") && (((__match_scrutinee_80)[1])?.type === "List")) {
        const predicate_78 = ((__match_scrutinee_80)[0]);
        return false;
      }
      if ((Array.isArray((__match_scrutinee_80))) && ((__match_scrutinee_80).length === 2) && (((__match_scrutinee_80)[1])?.tag === "Link") && (((__match_scrutinee_80)[1])?.type === "List")) {
        const predicate_78 = ((__match_scrutinee_80)[0]);
        const x_81 = (((__match_scrutinee_80)[1])._0);
        const rest_82 = (((__match_scrutinee_80)[1])._1);
        return (() => {
          const __match_scrutinee_83 = (predicate_78)(x_81);
          if (((__match_scrutinee_83) === true)) {
            return true;
          }
          if (((__match_scrutinee_83) === false)) {
            return (listAny)(predicate_78, rest_82);
          }
          throw new Error("Non-exhaustive patterns at runtime");
        })();
      }
      throw new Error("Non-exhaustive patterns at runtime");
    })();
  };
  return listAny;
})();
const listAll = (() => {
  const listAll = (predicate_84, list_85) => {
    return (() => {
      const __match_scrutinee_86 = [predicate_84, list_85];
      if ((Array.isArray((__match_scrutinee_86))) && ((__match_scrutinee_86).length === 2) && (((__match_scrutinee_86)[1])?.tag === "Empty") && (((__match_scrutinee_86)[1])?.type === "List")) {
        const predicate_84 = ((__match_scrutinee_86)[0]);
        return true;
      }
      if ((Array.isArray((__match_scrutinee_86))) && ((__match_scrutinee_86).length === 2) && (((__match_scrutinee_86)[1])?.tag === "Link") && (((__match_scrutinee_86)[1])?.type === "List")) {
        const predicate_84 = ((__match_scrutinee_86)[0]);
        const x_87 = (((__match_scrutinee_86)[1])._0);
        const rest_88 = (((__match_scrutinee_86)[1])._1);
        return (() => {
          const __match_scrutinee_89 = (predicate_84)(x_87);
          if (((__match_scrutinee_89) === false)) {
            return false;
          }
          if (((__match_scrutinee_89) === true)) {
            return (listAll)(predicate_84, rest_88);
          }
          throw new Error("Non-exhaustive patterns at runtime");
        })();
      }
      throw new Error("Non-exhaustive patterns at runtime");
    })();
  };
  return listAll;
})();
const listZip = (() => {
  const listZip = (xs_90, ys_91) => {
    return (() => {
      const __match_scrutinee_92 = [xs_90, ys_91];
      if ((Array.isArray((__match_scrutinee_92))) && ((__match_scrutinee_92).length === 2) && (((__match_scrutinee_92)[0])?.tag === "Empty") && (((__match_scrutinee_92)[0])?.type === "List")) {
        return ({ tag: "Empty", type: "List"});
      }
      if ((Array.isArray((__match_scrutinee_92))) && ((__match_scrutinee_92).length === 2) && (((__match_scrutinee_92)[1])?.tag === "Empty") && (((__match_scrutinee_92)[1])?.type === "List")) {
        return ({ tag: "Empty", type: "List"});
      }
      if ((Array.isArray((__match_scrutinee_92))) && ((__match_scrutinee_92).length === 2) && (((__match_scrutinee_92)[0])?.tag === "Link") && (((__match_scrutinee_92)[0])?.type === "List") && (((__match_scrutinee_92)[1])?.tag === "Link") && (((__match_scrutinee_92)[1])?.type === "List")) {
        const x_93 = (((__match_scrutinee_92)[0])._0);
        const restX = (((__match_scrutinee_92)[0])._1);
        const y = (((__match_scrutinee_92)[1])._0);
        const restY = (((__match_scrutinee_92)[1])._1);
        return ({ tag: "Link", type: "List",
          _0: [x_93, y],
          _1: (listZip)(restX, restY)
        });
      }
      throw new Error("Non-exhaustive patterns at runtime");
    })();
  };
  return listZip;
})();
const listPartition = (() => {
  const listPartition = (predicate_94, list_95) => {
    return (() => {
      const __match_scrutinee_96 = [predicate_94, list_95];
      if ((Array.isArray((__match_scrutinee_96))) && ((__match_scrutinee_96).length === 2) && (((__match_scrutinee_96)[1])?.tag === "Empty") && (((__match_scrutinee_96)[1])?.type === "List")) {
        const predicate_94 = ((__match_scrutinee_96)[0]);
        return ({ "trues": ({ tag: "Empty", type: "List"}), "falses": ({ tag: "Empty", type: "List"}) });
      }
      if ((Array.isArray((__match_scrutinee_96))) && ((__match_scrutinee_96).length === 2) && (((__match_scrutinee_96)[1])?.tag === "Link") && (((__match_scrutinee_96)[1])?.type === "List")) {
        const predicate_94 = ((__match_scrutinee_96)[0]);
        const x_97 = (((__match_scrutinee_96)[1])._0);
        const rest_98 = (((__match_scrutinee_96)[1])._1);
        return (() => {
          const partitioned = (listPartition)(predicate_94, rest_98);
          return (() => {
            const __match_scrutinee_99 = (predicate_94)(x_97);
            if (((__match_scrutinee_99) === true)) {
              return ({ "trues": ({ tag: "Link", type: "List",
                _0: x_97,
                _1: recordGetInfectious(partitioned, "trues")
              }), "falses": recordGetInfectious(partitioned, "falses") });
            }
            if (((__match_scrutinee_99) === false)) {
              return ({ "trues": recordGetInfectious(partitioned, "trues"), "falses": ({ tag: "Link", type: "List",
                _0: x_97,
                _1: recordGetInfectious(partitioned, "falses")
              }) });
            }
            throw new Error("Non-exhaustive patterns at runtime");
          })();
        })();
      }
      throw new Error("Non-exhaustive patterns at runtime");
    })();
  };
  return listPartition;
})();
export { listLength, listAppend, listMap, listFilter, listTake, listDrop, listSlice, listAt, listFoldl, listFoldr, listReverse, listRange, listInsertBy, listInsertionSortBy, listSortInt, listJoin, listForEach, listFlatMap, listFind, listAny, listAll, listZip, listPartition };
