// Generated by Workman compiler
import { stringFromLiteral as stringFromLit, stringToList as strToList, listToString as listToStr } from "./core/string.mjs";
import { strConcat as listConcat, strLength as listLength, strSlice as listSlice, strEq as listEq, intToString as listIntToString } from "./string.mjs";
import { charEq, add, sub, mul, div, cmpInt, eq, neq, lt, gt, lte, gte, boolAnd, boolOr, not, print } from "./prelude.mjs";
const stringFromLiteral = stringFromLit;
const stringToList = strToList;
const listToString = listToStr;
const stringConcat = (a, b) => (listToStr)((listConcat)((strToList)(a), (strToList)(b)));
const stringLength = (s) => (listLength)((strToList)(s));
const stringSlice = (s_0, start, end) => (listToStr)((listSlice)((strToList)(s_0), start, end));
const stringEq = (a_1, b_2) => (listEq)((strToList)(a_1), (strToList)(b_2));
const intToString = (n) => (listToStr)((listIntToString)(n));
export { stringFromLiteral, stringToList, listToString, stringConcat, stringLength, stringSlice, stringEq, intToString };
