// Generated by Workman compiler
import { strFromLiteral } from "./core/string.mjs";
import { Some, None } from "./option/core.mjs";
import { Empty, Link } from "./list/core.mjs";
import { intAdd as add, intSub as sub, intMul as mul, intDiv as div, intCompare as cmpInt, intEq as eq } from "./core/int.mjs";
import { LT, EQ, GT } from "./core/ordering.mjs";
import { Ok, Err } from "./result/core.mjs";
import { charEq, neq, lt, gt, lte, gte, boolAnd, boolOr, not, print } from "./prelude.mjs";
import { wrapResultValue } from "../runtime.mjs";
const EmptyLiteral = Object.freeze({ tag: "EmptyLiteral", type: "CharLiteralErrorInternal" });
const MultiCharLiteral = Object.freeze({ tag: "MultiCharLiteral", type: "CharLiteralErrorInternal" });
const CharLiteralErrorInternal = Object.freeze({ tag: "CharLiteralErrorInternal", type: "CharLiteralError" });
const fromLiteral = (literal) => (strFromLiteral)(literal);
const char = (literal_0) => {
  return (() => {
    const __match_scrutinee = (strFromLiteral)(literal_0);
    if (((__match_scrutinee)?.tag === "Empty") && ((__match_scrutinee)?.type === "List")) {
      return ({ tag: "Err", type: "Result",
        _0: ({ tag: "EmptyLiteral", type: "CharLiteralErrorInternal"})
      });
    }
    if (((__match_scrutinee)?.tag === "Link") && ((__match_scrutinee)?.type === "List")) {
      const code = ((__match_scrutinee)._0);
      const rest = ((__match_scrutinee)._1);
      return (() => {
        const __match_scrutinee_1 = rest;
        if (((__match_scrutinee_1)?.tag === "Empty") && ((__match_scrutinee_1)?.type === "List")) {
          return wrapResultValue(code);
        }
        if (true) {
          return ({ tag: "Err", type: "Result",
            _0: ({ tag: "MultiCharLiteral", type: "CharLiteralErrorInternal"})
          });
        }
        throw new Error("Non-exhaustive patterns at runtime");
      })();
    }
    throw new Error("Non-exhaustive patterns at runtime");
  })();
};
const charSpace = () => 32;
const charTab = () => 9;
const charNewline = () => 10;
const charReturn = () => 13;
const char0 = () => 48;
const char9 = () => 57;
const charA = () => 65;
const charZ = () => 90;
const charLowerA = () => 97;
const charLowerZ = () => 122;
const strLength = (() => {
  const strLength = (s) => {
    return (() => {
      const __match_scrutinee_2 = s;
      if (((__match_scrutinee_2)?.tag === "Empty") && ((__match_scrutinee_2)?.type === "List")) {
        return 0;
      }
      if (((__match_scrutinee_2)?.tag === "Link") && ((__match_scrutinee_2)?.type === "List")) {
        const rest_3 = ((__match_scrutinee_2)._1);
        return (add)(1, (strLength)(rest_3));
      }
      throw new Error("Non-exhaustive patterns at runtime");
    })();
  };
  return strLength;
})();
const strIsEmpty = (s_4) => {
  return (() => {
    const __match_scrutinee_5 = s_4;
    if (((__match_scrutinee_5)?.tag === "Empty") && ((__match_scrutinee_5)?.type === "List")) {
      return true;
    }
    if (true) {
      return false;
    }
    throw new Error("Non-exhaustive patterns at runtime");
  })();
};
const strCharAt = (() => {
  const strCharAt = (s_6, n) => {
    return (() => {
      const __match_scrutinee_7 = [s_6, n];
      if ((Array.isArray((__match_scrutinee_7))) && ((__match_scrutinee_7).length === 2) && (((__match_scrutinee_7)[0])?.tag === "Empty") && (((__match_scrutinee_7)[0])?.type === "List")) {
        return ({ tag: "None", type: "Option"});
      }
      if ((Array.isArray((__match_scrutinee_7))) && ((__match_scrutinee_7).length === 2) && (((__match_scrutinee_7)[0])?.tag === "Link") && (((__match_scrutinee_7)[0])?.type === "List") && (((__match_scrutinee_7)[1]) === 0)) {
        const c = (((__match_scrutinee_7)[0])._0);
        return ({ tag: "Some", type: "Option",
          _0: c
        });
      }
      if ((Array.isArray((__match_scrutinee_7))) && ((__match_scrutinee_7).length === 2) && (((__match_scrutinee_7)[0])?.tag === "Link") && (((__match_scrutinee_7)[0])?.type === "List")) {
        const rest_8 = (((__match_scrutinee_7)[0])._1);
        const idx = ((__match_scrutinee_7)[1]);
        return (strCharAt)(rest_8, (sub)(idx, 1));
      }
      throw new Error("Non-exhaustive patterns at runtime");
    })();
  };
  return strCharAt;
})();
const strTake = (() => {
  const strTake = (s_9, n_10) => {
    return (() => {
      const __match_scrutinee_11 = [s_9, n_10];
      if ((Array.isArray((__match_scrutinee_11))) && ((__match_scrutinee_11).length === 2) && (((__match_scrutinee_11)[1]) === 0)) {
        return ({ tag: "Empty", type: "List"});
      }
      if ((Array.isArray((__match_scrutinee_11))) && ((__match_scrutinee_11).length === 2) && (((__match_scrutinee_11)[0])?.tag === "Empty") && (((__match_scrutinee_11)[0])?.type === "List")) {
        return ({ tag: "Empty", type: "List"});
      }
      if ((Array.isArray((__match_scrutinee_11))) && ((__match_scrutinee_11).length === 2) && (((__match_scrutinee_11)[0])?.tag === "Link") && (((__match_scrutinee_11)[0])?.type === "List")) {
        const c_12 = (((__match_scrutinee_11)[0])._0);
        const rest_13 = (((__match_scrutinee_11)[0])._1);
        const count = ((__match_scrutinee_11)[1]);
        return ({ tag: "Link", type: "List",
          _0: c_12,
          _1: (strTake)(rest_13, (sub)(count, 1))
        });
      }
      throw new Error("Non-exhaustive patterns at runtime");
    })();
  };
  return strTake;
})();
const strDrop = (() => {
  const strDrop = (s_14, n_15) => {
    return (() => {
      const __match_scrutinee_16 = [s_14, n_15];
      if ((Array.isArray((__match_scrutinee_16))) && ((__match_scrutinee_16).length === 2) && (((__match_scrutinee_16)[1]) === 0)) {
        const value = ((__match_scrutinee_16)[0]);
        return value;
      }
      if ((Array.isArray((__match_scrutinee_16))) && ((__match_scrutinee_16).length === 2) && (((__match_scrutinee_16)[0])?.tag === "Empty") && (((__match_scrutinee_16)[0])?.type === "List")) {
        return ({ tag: "Empty", type: "List"});
      }
      if ((Array.isArray((__match_scrutinee_16))) && ((__match_scrutinee_16).length === 2) && (((__match_scrutinee_16)[0])?.tag === "Link") && (((__match_scrutinee_16)[0])?.type === "List")) {
        const rest_17 = (((__match_scrutinee_16)[0])._1);
        const count_18 = ((__match_scrutinee_16)[1]);
        return (strDrop)(rest_17, (sub)(count_18, 1));
      }
      throw new Error("Non-exhaustive patterns at runtime");
    })();
  };
  return strDrop;
})();
const strSlice = (s_19, start, end) => {
  return (() => {
    const dropped = () => (strDrop)(s_19, start);
    return (() => {
      const len = () => (sub)(end, start);
      return (strTake)((dropped)(), (len)());
    })();
  })();
};
const strConcat = (() => {
  const strConcat = (s1, s2) => {
    return (() => {
      const __match_scrutinee_20 = [s1, s2];
      if ((Array.isArray((__match_scrutinee_20))) && ((__match_scrutinee_20).length === 2) && (((__match_scrutinee_20)[0])?.tag === "Empty") && (((__match_scrutinee_20)[0])?.type === "List")) {
        const tail = ((__match_scrutinee_20)[1]);
        return tail;
      }
      if ((Array.isArray((__match_scrutinee_20))) && ((__match_scrutinee_20).length === 2) && (((__match_scrutinee_20)[0])?.tag === "Link") && (((__match_scrutinee_20)[0])?.type === "List")) {
        const c_21 = (((__match_scrutinee_20)[0])._0);
        const rest_22 = (((__match_scrutinee_20)[0])._1);
        const tail_23 = ((__match_scrutinee_20)[1]);
        return ({ tag: "Link", type: "List",
          _0: c_21,
          _1: (strConcat)(rest_22, tail_23)
        });
      }
      throw new Error("Non-exhaustive patterns at runtime");
    })();
  };
  return strConcat;
})();
const isDigit = (c_24) => {
  return (() => {
    const ge0 = () => {
      return (() => {
        const __match_scrutinee_25 = (cmpInt)(c_24, (char0)());
        if (((__match_scrutinee_25)?.tag === "LT") && ((__match_scrutinee_25)?.type === "Ordering")) {
          return false;
        }
        if (true) {
          return true;
        }
        throw new Error("Non-exhaustive patterns at runtime");
      })();
    };
    return (() => {
      const le9 = () => {
        return (() => {
          const __match_scrutinee_26 = (cmpInt)(c_24, (char9)());
          if (((__match_scrutinee_26)?.tag === "GT") && ((__match_scrutinee_26)?.type === "Ordering")) {
            return false;
          }
          if (true) {
            return true;
          }
          throw new Error("Non-exhaustive patterns at runtime");
        })();
      };
      return (() => {
        const __match_scrutinee_27 = (ge0)();
        if (((__match_scrutinee_27) === false)) {
          return false;
        }
        if (((__match_scrutinee_27) === true)) {
          return (le9)();
        }
        throw new Error("Non-exhaustive patterns at runtime");
      })();
    })();
  })();
};
const isUppercase = (c_28) => {
  return (() => {
    const geA = () => {
      return (() => {
        const __match_scrutinee_29 = (cmpInt)(c_28, (charA)());
        if (((__match_scrutinee_29)?.tag === "LT") && ((__match_scrutinee_29)?.type === "Ordering")) {
          return false;
        }
        if (true) {
          return true;
        }
        throw new Error("Non-exhaustive patterns at runtime");
      })();
    };
    return (() => {
      const leZ = () => {
        return (() => {
          const __match_scrutinee_30 = (cmpInt)(c_28, (charZ)());
          if (((__match_scrutinee_30)?.tag === "GT") && ((__match_scrutinee_30)?.type === "Ordering")) {
            return false;
          }
          if (true) {
            return true;
          }
          throw new Error("Non-exhaustive patterns at runtime");
        })();
      };
      return (() => {
        const __match_scrutinee_31 = (geA)();
        if (((__match_scrutinee_31) === false)) {
          return false;
        }
        if (((__match_scrutinee_31) === true)) {
          return (leZ)();
        }
        throw new Error("Non-exhaustive patterns at runtime");
      })();
    })();
  })();
};
const isLowercase = (c_32) => {
  return (() => {
    const gea = () => {
      return (() => {
        const __match_scrutinee_33 = (cmpInt)(c_32, (charLowerA)());
        if (((__match_scrutinee_33)?.tag === "LT") && ((__match_scrutinee_33)?.type === "Ordering")) {
          return false;
        }
        if (true) {
          return true;
        }
        throw new Error("Non-exhaustive patterns at runtime");
      })();
    };
    return (() => {
      const lez = () => {
        return (() => {
          const __match_scrutinee_34 = (cmpInt)(c_32, (charLowerZ)());
          if (((__match_scrutinee_34)?.tag === "GT") && ((__match_scrutinee_34)?.type === "Ordering")) {
            return false;
          }
          if (true) {
            return true;
          }
          throw new Error("Non-exhaustive patterns at runtime");
        })();
      };
      return (() => {
        const __match_scrutinee_35 = (gea)();
        if (((__match_scrutinee_35) === false)) {
          return false;
        }
        if (((__match_scrutinee_35) === true)) {
          return (lez)();
        }
        throw new Error("Non-exhaustive patterns at runtime");
      })();
    })();
  })();
};
const isAlpha = (c_36) => {
  return (() => {
    const __match_scrutinee_37 = (isUppercase)(c_36);
    if (((__match_scrutinee_37) === true)) {
      return true;
    }
    if (((__match_scrutinee_37) === false)) {
      return (isLowercase)(c_36);
    }
    throw new Error("Non-exhaustive patterns at runtime");
  })();
};
const isAlphaNum = (c_38) => {
  return (() => {
    const __match_scrutinee_39 = (isAlpha)(c_38);
    if (((__match_scrutinee_39) === true)) {
      return true;
    }
    if (((__match_scrutinee_39) === false)) {
      return (isDigit)(c_38);
    }
    throw new Error("Non-exhaustive patterns at runtime");
  })();
};
const isWhitespace = (c_40) => {
  return (() => {
    const __match_scrutinee_41 = (eq)(c_40, (charSpace)());
    if (((__match_scrutinee_41) === true)) {
      return true;
    }
    if (((__match_scrutinee_41) === false)) {
      return (() => {
        const __match_scrutinee_42 = (eq)(c_40, (charTab)());
        if (((__match_scrutinee_42) === true)) {
          return true;
        }
        if (((__match_scrutinee_42) === false)) {
          return (() => {
            const __match_scrutinee_43 = (eq)(c_40, (charNewline)());
            if (((__match_scrutinee_43) === true)) {
              return true;
            }
            if (((__match_scrutinee_43) === false)) {
              return (eq)(c_40, (charReturn)());
            }
            throw new Error("Non-exhaustive patterns at runtime");
          })();
        }
        throw new Error("Non-exhaustive patterns at runtime");
      })();
    }
    throw new Error("Non-exhaustive patterns at runtime");
  })();
};
const strEq = (() => {
  const strEq = (s1_44, s2_45) => {
    return (() => {
      const __match_scrutinee_46 = [s1_44, s2_45];
      if ((Array.isArray((__match_scrutinee_46))) && ((__match_scrutinee_46).length === 2) && (((__match_scrutinee_46)[0])?.tag === "Empty") && (((__match_scrutinee_46)[0])?.type === "List") && (((__match_scrutinee_46)[1])?.tag === "Empty") && (((__match_scrutinee_46)[1])?.type === "List")) {
        return true;
      }
      if ((Array.isArray((__match_scrutinee_46))) && ((__match_scrutinee_46).length === 2) && (((__match_scrutinee_46)[0])?.tag === "Empty") && (((__match_scrutinee_46)[0])?.type === "List")) {
        return false;
      }
      if ((Array.isArray((__match_scrutinee_46))) && ((__match_scrutinee_46).length === 2) && (((__match_scrutinee_46)[1])?.tag === "Empty") && (((__match_scrutinee_46)[1])?.type === "List")) {
        return false;
      }
      if ((Array.isArray((__match_scrutinee_46))) && ((__match_scrutinee_46).length === 2) && (((__match_scrutinee_46)[0])?.tag === "Link") && (((__match_scrutinee_46)[0])?.type === "List") && (((__match_scrutinee_46)[1])?.tag === "Link") && (((__match_scrutinee_46)[1])?.type === "List")) {
        const c1 = (((__match_scrutinee_46)[0])._0);
        const rest1 = (((__match_scrutinee_46)[0])._1);
        const c2 = (((__match_scrutinee_46)[1])._0);
        const rest2 = (((__match_scrutinee_46)[1])._1);
        return (() => {
          const __match_scrutinee_47 = (eq)(c1, c2);
          if (((__match_scrutinee_47) === false)) {
            return false;
          }
          if (((__match_scrutinee_47) === true)) {
            return (strEq)(rest1, rest2);
          }
          throw new Error("Non-exhaustive patterns at runtime");
        })();
      }
      throw new Error("Non-exhaustive patterns at runtime");
    })();
  };
  return strEq;
})();
const digitToChar = (n_48) => (add)((char0)(), n_48);
const charToDigit = (c_49, error) => {
  return (() => {
    const __match_scrutinee_50 = (isDigit)(c_49);
    if (((__match_scrutinee_50) === false)) {
      return ({ tag: "Err", type: "Result",
        _0: error
      });
    }
    if (((__match_scrutinee_50) === true)) {
      return wrapResultValue((sub)(c_49, (char0)()));
    }
    throw new Error("Non-exhaustive patterns at runtime");
  })();
};
const intToStringPositive = (() => {
  const intToStringPositive = (n_51) => {
    return (() => {
      const __match_scrutinee_52 = (eq)(n_51, 0);
      if (((__match_scrutinee_52) === true)) {
        return ({ tag: "Empty", type: "List"});
      }
      if (((__match_scrutinee_52) === false)) {
        return (() => {
          const digit = (digitToChar)((sub)(n_51, (mul)((div)(n_51, 10), 10)));
          return (() => {
            const rest_53 = (intToStringPositive)((div)(n_51, 10));
            return (strConcat)(rest_53, ({ tag: "Link", type: "List",
              _0: digit,
              _1: ({ tag: "Empty", type: "List"})
            }));
          })();
        })();
      }
      throw new Error("Non-exhaustive patterns at runtime");
    })();
  };
  return intToStringPositive;
})();
const intToString = (n_54) => {
  return (() => {
    const __match_scrutinee_55 = (eq)(n_54, 0);
    if (((__match_scrutinee_55) === true)) {
      return ({ tag: "Link", type: "List",
        _0: (char0)(),
        _1: ({ tag: "Empty", type: "List"})
      });
    }
    if (((__match_scrutinee_55) === false)) {
      return (() => {
        const __match_scrutinee_56 = (cmpInt)(n_54, 0);
        if (((__match_scrutinee_56)?.tag === "LT") && ((__match_scrutinee_56)?.type === "Ordering")) {
          return (() => {
            const absStr = (intToStringPositive)((sub)(0, n_54));
            return ({ tag: "Link", type: "List",
              _0: 45,
              _1: absStr
            });
          })();
        }
        if (true) {
          return (intToStringPositive)(n_54);
        }
        throw new Error("Non-exhaustive patterns at runtime");
      })();
    }
    throw new Error("Non-exhaustive patterns at runtime");
  })();
};
const strStartsWith = (() => {
  const strStartsWith = (str, pre) => {
    return (() => {
      const __match_scrutinee_57 = [str, pre];
      if ((Array.isArray((__match_scrutinee_57))) && ((__match_scrutinee_57).length === 2) && (((__match_scrutinee_57)[1])?.tag === "Empty") && (((__match_scrutinee_57)[1])?.type === "List")) {
        return true;
      }
      if ((Array.isArray((__match_scrutinee_57))) && ((__match_scrutinee_57).length === 2) && (((__match_scrutinee_57)[0])?.tag === "Empty") && (((__match_scrutinee_57)[0])?.type === "List")) {
        return false;
      }
      if ((Array.isArray((__match_scrutinee_57))) && ((__match_scrutinee_57).length === 2) && (((__match_scrutinee_57)[0])?.tag === "Link") && (((__match_scrutinee_57)[0])?.type === "List") && (((__match_scrutinee_57)[1])?.tag === "Link") && (((__match_scrutinee_57)[1])?.type === "List")) {
        const c1_58 = (((__match_scrutinee_57)[0])._0);
        const rest1_59 = (((__match_scrutinee_57)[0])._1);
        const c2_60 = (((__match_scrutinee_57)[1])._0);
        const rest2_61 = (((__match_scrutinee_57)[1])._1);
        return (() => {
          const __match_scrutinee_62 = (eq)(c1_58, c2_60);
          if (((__match_scrutinee_62) === false)) {
            return false;
          }
          if (((__match_scrutinee_62) === true)) {
            return (strStartsWith)(rest1_59, rest2_61);
          }
          throw new Error("Non-exhaustive patterns at runtime");
        })();
      }
      throw new Error("Non-exhaustive patterns at runtime");
    })();
  };
  return strStartsWith;
})();
const strEndsWith = (str_63, suffix) => {
  return (() => {
    const strLen = (strLength)(str_63);
    return (() => {
      const suffixLen = (strLength)(suffix);
      return (() => {
        const __match_scrutinee_64 = (cmpInt)(suffixLen, strLen);
        if (((__match_scrutinee_64)?.tag === "GT") && ((__match_scrutinee_64)?.type === "Ordering")) {
          return false;
        }
        if (true) {
          return (() => {
            const start_65 = (sub)(strLen, suffixLen);
            return (strEq)((strDrop)(str_63, start_65), suffix);
          })();
        }
        throw new Error("Non-exhaustive patterns at runtime");
      })();
    })();
  })();
};
const strContainsAt = (() => {
  const strContainsAt = (haystack, needle, pos) => {
    return (() => {
      const __match_scrutinee_66 = [haystack, needle, pos];
      if ((Array.isArray((__match_scrutinee_66))) && ((__match_scrutinee_66).length === 3)) {
        const haystack = ((__match_scrutinee_66)[0]);
        const needle = ((__match_scrutinee_66)[1]);
        const pos = ((__match_scrutinee_66)[2]);
        return (() => {
          const __match_scrutinee_67 = (strStartsWith)((strDrop)(haystack, pos), needle);
          if (((__match_scrutinee_67) === true)) {
            return true;
          }
          if (((__match_scrutinee_67) === false)) {
            return (() => {
              const nextPos = (add)(pos, 1);
              return (() => {
                const __match_scrutinee_68 = (cmpInt)(nextPos, (strLength)(haystack));
                if (((__match_scrutinee_68)?.tag === "GT") && ((__match_scrutinee_68)?.type === "Ordering")) {
                  return false;
                }
                if (true) {
                  return (strContainsAt)(haystack, needle, nextPos);
                }
                throw new Error("Non-exhaustive patterns at runtime");
              })();
            })();
          }
          throw new Error("Non-exhaustive patterns at runtime");
        })();
      }
      throw new Error("Non-exhaustive patterns at runtime");
    })();
  };
  return strContainsAt;
})();
const strContains = (haystack_69, needle_70) => {
  return (() => {
    const __match_scrutinee_71 = (strIsEmpty)(needle_70);
    if (((__match_scrutinee_71) === true)) {
      return true;
    }
    if (((__match_scrutinee_71) === false)) {
      return (strContainsAt)(haystack_69, needle_70, 0);
    }
    throw new Error("Non-exhaustive patterns at runtime");
  })();
};
const strSplitHelper = (() => {
  const strSplitHelper = (str_72, delim, acc, current) => {
    return (() => {
      const __match_scrutinee_73 = [str_72, delim, acc, current];
      if ((Array.isArray((__match_scrutinee_73))) && ((__match_scrutinee_73).length === 4) && (((__match_scrutinee_73)[0])?.tag === "Empty") && (((__match_scrutinee_73)[0])?.type === "List")) {
        const delim = ((__match_scrutinee_73)[1]);
        const acc = ((__match_scrutinee_73)[2]);
        const current = ((__match_scrutinee_73)[3]);
        return (() => {
          const __match_scrutinee_74 = (strIsEmpty)(current);
          if (((__match_scrutinee_74) === true)) {
            return acc;
          }
          if (((__match_scrutinee_74) === false)) {
            return ({ tag: "Link", type: "List",
              _0: current,
              _1: acc
            });
          }
          throw new Error("Non-exhaustive patterns at runtime");
        })();
      }
      if ((Array.isArray((__match_scrutinee_73))) && ((__match_scrutinee_73).length === 4) && (((__match_scrutinee_73)[0])?.tag === "Link") && (((__match_scrutinee_73)[0])?.type === "List")) {
        const c_75 = (((__match_scrutinee_73)[0])._0);
        const rest_76 = (((__match_scrutinee_73)[0])._1);
        const delim = ((__match_scrutinee_73)[1]);
        const acc = ((__match_scrutinee_73)[2]);
        const current = ((__match_scrutinee_73)[3]);
        return (() => {
          const __match_scrutinee_77 = (strStartsWith)(({ tag: "Link", type: "List",
            _0: c_75,
            _1: rest_76
          }), delim);
          if (((__match_scrutinee_77) === true)) {
            return (() => {
              const newAcc = ({ tag: "Link", type: "List",
                _0: current,
                _1: acc
              });
              return (() => {
                const afterDelim = (strDrop)(({ tag: "Link", type: "List",
                  _0: c_75,
                  _1: rest_76
                }), (strLength)(delim));
                return (strSplitHelper)(afterDelim, delim, newAcc, ({ tag: "Empty", type: "List"}));
              })();
            })();
          }
          if (((__match_scrutinee_77) === false)) {
            return (strSplitHelper)(rest_76, delim, acc, ({ tag: "Link", type: "List",
              _0: c_75,
              _1: current
            }));
          }
          throw new Error("Non-exhaustive patterns at runtime");
        })();
      }
      throw new Error("Non-exhaustive patterns at runtime");
    })();
  };
  return strSplitHelper;
})();
const strSplit = (str_78, delim_79) => {
  return (() => {
    const reverseList = (() => {
      const reverseList = (list, acc_80) => {
        return (() => {
          const __match_scrutinee_81 = [list, acc_80];
          if ((Array.isArray((__match_scrutinee_81))) && ((__match_scrutinee_81).length === 2) && (((__match_scrutinee_81)[0])?.tag === "Empty") && (((__match_scrutinee_81)[0])?.type === "List")) {
            const acc_80 = ((__match_scrutinee_81)[1]);
            return acc_80;
          }
          if ((Array.isArray((__match_scrutinee_81))) && ((__match_scrutinee_81).length === 2) && (((__match_scrutinee_81)[0])?.tag === "Link") && (((__match_scrutinee_81)[0])?.type === "List")) {
            const x = (((__match_scrutinee_81)[0])._0);
            const rest_82 = (((__match_scrutinee_81)[0])._1);
            const acc_80 = ((__match_scrutinee_81)[1]);
            return (reverseList)(rest_82, ({ tag: "Link", type: "List",
              _0: x,
              _1: acc_80
            }));
          }
          throw new Error("Non-exhaustive patterns at runtime");
        })();
      };
      return reverseList;
    })();
    return (() => {
      const reverseAll = (() => {
        const reverseAll = (list_83) => {
          return (() => {
            const __match_scrutinee_84 = list_83;
            if (((__match_scrutinee_84)?.tag === "Empty") && ((__match_scrutinee_84)?.type === "List")) {
              return ({ tag: "Empty", type: "List"});
            }
            if (((__match_scrutinee_84)?.tag === "Link") && ((__match_scrutinee_84)?.type === "List")) {
              const x_85 = ((__match_scrutinee_84)._0);
              const rest_86 = ((__match_scrutinee_84)._1);
              return ({ tag: "Link", type: "List",
                _0: (reverseList)(x_85, ({ tag: "Empty", type: "List"})),
                _1: (reverseAll)(rest_86)
              });
            }
            throw new Error("Non-exhaustive patterns at runtime");
          })();
        };
        return reverseAll;
      })();
      return (() => {
        const __match_scrutinee_87 = (strIsEmpty)(delim_79);
        if (((__match_scrutinee_87) === true)) {
          return ({ tag: "Link", type: "List",
            _0: str_78,
            _1: ({ tag: "Empty", type: "List"})
          });
        }
        if (((__match_scrutinee_87) === false)) {
          return (() => {
            const parts = (strSplitHelper)(str_78, delim_79, ({ tag: "Empty", type: "List"}), ({ tag: "Empty", type: "List"}));
            return (reverseAll)((reverseList)(parts, ({ tag: "Empty", type: "List"})));
          })();
        }
        throw new Error("Non-exhaustive patterns at runtime");
      })();
    })();
  })();
};
const strTrimStart = (() => {
  const strTrimStart = (s_88) => {
    return (() => {
      const __match_scrutinee_89 = s_88;
      if (((__match_scrutinee_89)?.tag === "Empty") && ((__match_scrutinee_89)?.type === "List")) {
        return ({ tag: "Empty", type: "List"});
      }
      if (((__match_scrutinee_89)?.tag === "Link") && ((__match_scrutinee_89)?.type === "List")) {
        const c_90 = ((__match_scrutinee_89)._0);
        const rest_91 = ((__match_scrutinee_89)._1);
        return (() => {
          const __match_scrutinee_92 = (isWhitespace)(c_90);
          if (((__match_scrutinee_92) === true)) {
            return (strTrimStart)(rest_91);
          }
          if (((__match_scrutinee_92) === false)) {
            return ({ tag: "Link", type: "List",
              _0: c_90,
              _1: rest_91
            });
          }
          throw new Error("Non-exhaustive patterns at runtime");
        })();
      }
      throw new Error("Non-exhaustive patterns at runtime");
    })();
  };
  return strTrimStart;
})();
const strTrimEnd = (s_93) => {
  return (() => {
    const reverseList_94 = (() => {
      const reverseList_94 = (list_95, acc_96) => {
        return (() => {
          const __match_scrutinee_97 = [list_95, acc_96];
          if ((Array.isArray((__match_scrutinee_97))) && ((__match_scrutinee_97).length === 2) && (((__match_scrutinee_97)[0])?.tag === "Empty") && (((__match_scrutinee_97)[0])?.type === "List")) {
            const acc_96 = ((__match_scrutinee_97)[1]);
            return acc_96;
          }
          if ((Array.isArray((__match_scrutinee_97))) && ((__match_scrutinee_97).length === 2) && (((__match_scrutinee_97)[0])?.tag === "Link") && (((__match_scrutinee_97)[0])?.type === "List")) {
            const x_98 = (((__match_scrutinee_97)[0])._0);
            const rest_99 = (((__match_scrutinee_97)[0])._1);
            const acc_96 = ((__match_scrutinee_97)[1]);
            return (reverseList_94)(rest_99, ({ tag: "Link", type: "List",
              _0: x_98,
              _1: acc_96
            }));
          }
          throw new Error("Non-exhaustive patterns at runtime");
        })();
      };
      return reverseList_94;
    })();
    return (() => {
      const reversed = (reverseList_94)(s_93, ({ tag: "Empty", type: "List"}));
      return (() => {
        const trimmed = (strTrimStart)(reversed);
        return (reverseList_94)(trimmed, ({ tag: "Empty", type: "List"}));
      })();
    })();
  })();
};
const strTrim = (s_100) => (strTrimEnd)((strTrimStart)(s_100));
const strLines = (s_101) => {
  return (strSplit)(s_101, ({ tag: "Link", type: "List",
    _0: (charNewline)(),
    _1: ({ tag: "Empty", type: "List"})
  }));
};
const strJoin = (() => {
  const strJoin = (sep, strings) => {
    return (() => {
      const __match_scrutinee_102 = [sep, strings];
      if ((Array.isArray((__match_scrutinee_102))) && ((__match_scrutinee_102).length === 2) && (((__match_scrutinee_102)[1])?.tag === "Empty") && (((__match_scrutinee_102)[1])?.type === "List")) {
        const sep = ((__match_scrutinee_102)[0]);
        return ({ tag: "Empty", type: "List"});
      }
      if ((Array.isArray((__match_scrutinee_102))) && ((__match_scrutinee_102).length === 2) && (((__match_scrutinee_102)[1])?.tag === "Link") && (((__match_scrutinee_102)[1])?.type === "List") && ((((__match_scrutinee_102)[1])._1)?.tag === "Empty") && ((((__match_scrutinee_102)[1])._1)?.type === "List")) {
        const sep = ((__match_scrutinee_102)[0]);
        const s_103 = (((__match_scrutinee_102)[1])._0);
        return s_103;
      }
      if ((Array.isArray((__match_scrutinee_102))) && ((__match_scrutinee_102).length === 2) && (((__match_scrutinee_102)[1])?.tag === "Link") && (((__match_scrutinee_102)[1])?.type === "List")) {
        const sep = ((__match_scrutinee_102)[0]);
        const s_104 = (((__match_scrutinee_102)[1])._0);
        const rest_105 = (((__match_scrutinee_102)[1])._1);
        return (strConcat)(s_104, (strConcat)(sep, (strJoin)(sep, rest_105)));
      }
      throw new Error("Non-exhaustive patterns at runtime");
    })();
  };
  return strJoin;
})();
export { fromLiteral, char, charSpace, charTab, charNewline, charReturn, char0, char9, charA, charZ, charLowerA, charLowerZ, strLength, strIsEmpty, strCharAt, strTake, strDrop, strSlice, strConcat, isDigit, isUppercase, isLowercase, isAlpha, isAlphaNum, isWhitespace, strEq, digitToChar, charToDigit, intToString, strStartsWith, strEndsWith, strContains, strSplit, strTrimStart, strTrimEnd, strTrim, strLines, strJoin, CharLiteralErrorInternal };
