// Generated by Workman compiler
const boolNot = (value) => {
  return (() => {
    const __match_scrutinee = value;
    if (((__match_scrutinee) === true)) {
      return false;
    }
    if (((__match_scrutinee) === false)) {
      return true;
    }
    throw new Error("Non-exhaustive patterns at runtime");
  })();
};
const boolAnd = (left, right) => {
  return (() => {
    const __match_scrutinee_0 = left;
    if (((__match_scrutinee_0) === true)) {
      return right;
    }
    if (((__match_scrutinee_0) === false)) {
      return false;
    }
    throw new Error("Non-exhaustive patterns at runtime");
  })();
};
const boolOr = (left_1, right_2) => {
  return (() => {
    const __match_scrutinee_3 = left_1;
    if (((__match_scrutinee_3) === true)) {
      return true;
    }
    if (((__match_scrutinee_3) === false)) {
      return right_2;
    }
    throw new Error("Non-exhaustive patterns at runtime");
  })();
};
const __op___ = boolAnd;
export { boolNot, boolAnd, boolOr };
