// Generated by Workman compiler
import { EQ, LT, GT } from "./ordering.mjs";
import { nativeAdd, nativeSub, nativeMul, nativeDiv, nativeCmpInt } from "../../runtime.mjs";
const intAdd = (left, right) => (nativeAdd)(left, right);
const intSub = (left_8, right_9) => (nativeSub)(left_8, right_9);
const intMul = (left_10, right_11) => (nativeMul)(left_10, right_11);
const intDiv = (left_12, right_13) => (nativeDiv)(left_12, right_13);
const intCompare = (left_14, right_15) => (nativeCmpInt)(left_14, right_15);
const intEq = (left_16, right_17) => {
  return (() => {
    const __match_scrutinee = (intCompare)(left_16, right_17);
    if (((__match_scrutinee)?.tag === "EQ") && ((__match_scrutinee)?.type === "Ordering")) {
      return true;
    }
    if (true) {
      return false;
    }
    throw new Error("Non-exhaustive patterns at runtime");
  })();
};
const intNeq = (left_18, right_19) => {
  return (() => {
    const __match_scrutinee_20 = (intCompare)(left_18, right_19);
    if (((__match_scrutinee_20)?.tag === "EQ") && ((__match_scrutinee_20)?.type === "Ordering")) {
      return false;
    }
    if (true) {
      return true;
    }
    throw new Error("Non-exhaustive patterns at runtime");
  })();
};
const intLt = (left_21, right_22) => {
  return (() => {
    const __match_scrutinee_23 = (intCompare)(left_21, right_22);
    if (((__match_scrutinee_23)?.tag === "LT") && ((__match_scrutinee_23)?.type === "Ordering")) {
      return true;
    }
    if (true) {
      return false;
    }
    throw new Error("Non-exhaustive patterns at runtime");
  })();
};
const intLte = (left_24, right_25) => {
  return (() => {
    const __match_scrutinee_26 = (intCompare)(left_24, right_25);
    if (((__match_scrutinee_26)?.tag === "GT") && ((__match_scrutinee_26)?.type === "Ordering")) {
      return false;
    }
    if (true) {
      return true;
    }
    throw new Error("Non-exhaustive patterns at runtime");
  })();
};
const intGt = (left_27, right_28) => {
  return (() => {
    const __match_scrutinee_29 = (intCompare)(left_27, right_28);
    if (((__match_scrutinee_29)?.tag === "GT") && ((__match_scrutinee_29)?.type === "Ordering")) {
      return true;
    }
    if (true) {
      return false;
    }
    throw new Error("Non-exhaustive patterns at runtime");
  })();
};
const intGte = (left_30, right_31) => {
  return (() => {
    const __match_scrutinee_32 = (intCompare)(left_30, right_31);
    if (((__match_scrutinee_32)?.tag === "LT") && ((__match_scrutinee_32)?.type === "Ordering")) {
      return false;
    }
    if (true) {
      return true;
    }
    throw new Error("Non-exhaustive patterns at runtime");
  })();
};
const intMod = (left_33, right_34) => (intSub)(left_33, (intMul)((intDiv)(left_33, right_34), right_34));
const intIsEven = (n) => (intEq)((intMod)(n, 2), 0);
const __op__ = intAdd;
const __op___0 = intSub;
const __op___1 = intMul;
const __op___2 = intDiv;
const __op___ = intEq;
const __op____3 = intNeq;
const __op___4 = intLt;
const __op___5 = intGt;
const __op____6 = intLte;
const __op____7 = intGte;
export { intAdd, intSub, intMul, intDiv, intCompare, intEq, intNeq, intLt, intLte, intGt, intGte, intMod, intIsEven };
