// Generated by Workman compiler
const LT = Object.freeze({ tag: "LT", type: "Ordering" });
const EQ = Object.freeze({ tag: "EQ", type: "Ordering" });
const GT = Object.freeze({ tag: "GT", type: "Ordering" });
const lt = ({ tag: "LT", type: "Ordering"});
const eq = ({ tag: "EQ", type: "Ordering"});
const gt = ({ tag: "GT", type: "Ordering"});
export { lt, eq, gt, LT, EQ, GT };
