// Generated by Workman compiler
import { nativeStringFromLiteral, nativeStringToList, nativeListToString, nativeStrFromLiteral } from "../../runtime.mjs";
const stringFromLiteral = (lit) => (nativeStringFromLiteral)(lit);
const stringToList = (str) => (nativeStringToList)(str);
const listToString = (chars) => (nativeListToString)(chars);
const strFromLiteral = (lit_0) => (nativeStrFromLiteral)(lit_0);
export { stringFromLiteral, stringToList, listToString, strFromLiteral };
