// Generated by Workman compiler
import { char } from "../std/string.mjs";
import { stringToList } from "../std/nativeString.mjs";
import { listAt } from "../std/list.mjs";
import { charEq, add, sub, mul, div, cmpInt, eq, neq, lt, gt, lte, gte, boolAnd, boolOr, not, print } from "../std/prelude.mjs";
import { callInfectious, nativeStringFromLiteral } from "../runtime.mjs";
const char0 = callInfectious(char, nativeStringFromLiteral("0"));
const char9 = callInfectious(char, nativeStringFromLiteral("9"));
const charA = callInfectious(char, nativeStringFromLiteral("A"));
const charZ = callInfectious(char, nativeStringFromLiteral("Z"));
const chara = callInfectious(char, nativeStringFromLiteral("a"));
const charz = callInfectious(char, nativeStringFromLiteral("z"));
const charApostrophe = callInfectious(char, nativeStringFromLiteral("'"));
const isDigitCode = (charCode) => callInfectious(boolAnd, callInfectious(gte, charCode, char0), callInfectious(lte, charCode, char9));
const isUppercaseCode = (charCode_0) => callInfectious(boolAnd, callInfectious(gte, charCode_0, charA), callInfectious(lte, charCode_0, charZ));
const isLowercaseCode = (charCode_1) => callInfectious(boolAnd, callInfectious(gte, charCode_1, chara), callInfectious(lte, charCode_1, charz));
const isAlphaCode = (charCode_2) => callInfectious(boolOr, callInfectious(isUppercaseCode, charCode_2), callInfectious(isLowercaseCode, charCode_2));
const isAlphaNumericCode = (charCode_3) => callInfectious(boolOr, callInfectious(isAlphaCode, charCode_3), callInfectious(boolOr, callInfectious(isDigitCode, charCode_3), callInfectious(eq, charCode_3, charApostrophe)));
const isWhitespaceCode = (charCode_4) => {
  return (() => {
    const __match_scrutinee = charCode_4;
    if (((__match_scrutinee) === 32)) {
      return true;
    }
    if (((__match_scrutinee) === 9)) {
      return true;
    }
    if (((__match_scrutinee) === 10)) {
      return true;
    }
    if (((__match_scrutinee) === 13)) {
      return true;
    }
    if (true) {
      return false;
    }
    throw new Error("Non-exhaustive patterns at runtime");
  })();
};
const getCharCode = (str) => {
  return (() => {
    const codes = (stringToList)(str);
    return callInfectious(listAt, codes, 0, undefined);
  })();
};
const isDigit = (str_5) => {
  return (() => {
    const __match_scrutinee_6 = callInfectious(isDigitCode, callInfectious(getCharCode, str_5));
    if (((__match_scrutinee_6)?.tag === "Ok") && ((__match_scrutinee_6)?.type === "Result")) {
      const result = ((__match_scrutinee_6)._0);
      return result;
    }
    if (((__match_scrutinee_6)?.tag === "Err") && ((__match_scrutinee_6)?.type === "Result")) {
      return false;
    }
    throw new Error("Non-exhaustive patterns at runtime");
  })();
};
const isUppercase = (str_7) => {
  return (() => {
    const __match_scrutinee_8 = callInfectious(isUppercaseCode, callInfectious(getCharCode, str_7));
    if (((__match_scrutinee_8)?.tag === "Ok") && ((__match_scrutinee_8)?.type === "Result")) {
      const result_9 = ((__match_scrutinee_8)._0);
      return result_9;
    }
    if (((__match_scrutinee_8)?.tag === "Err") && ((__match_scrutinee_8)?.type === "Result")) {
      return false;
    }
    throw new Error("Non-exhaustive patterns at runtime");
  })();
};
const isLowercase = (str_10) => {
  return (() => {
    const __match_scrutinee_11 = callInfectious(isLowercaseCode, callInfectious(getCharCode, str_10));
    if (((__match_scrutinee_11)?.tag === "Ok") && ((__match_scrutinee_11)?.type === "Result")) {
      const result_12 = ((__match_scrutinee_11)._0);
      return result_12;
    }
    if (((__match_scrutinee_11)?.tag === "Err") && ((__match_scrutinee_11)?.type === "Result")) {
      return false;
    }
    throw new Error("Non-exhaustive patterns at runtime");
  })();
};
const isAlpha = (str_13) => {
  return (() => {
    const __match_scrutinee_14 = callInfectious(isAlphaCode, callInfectious(getCharCode, str_13));
    if (((__match_scrutinee_14)?.tag === "Ok") && ((__match_scrutinee_14)?.type === "Result")) {
      const result_15 = ((__match_scrutinee_14)._0);
      return result_15;
    }
    if (((__match_scrutinee_14)?.tag === "Err") && ((__match_scrutinee_14)?.type === "Result")) {
      return false;
    }
    throw new Error("Non-exhaustive patterns at runtime");
  })();
};
const isAlphaNumeric = (str_16) => {
  return (() => {
    const __match_scrutinee_17 = callInfectious(isAlphaNumericCode, callInfectious(getCharCode, str_16));
    if (((__match_scrutinee_17)?.tag === "Ok") && ((__match_scrutinee_17)?.type === "Result")) {
      const result_18 = ((__match_scrutinee_17)._0);
      return result_18;
    }
    if (((__match_scrutinee_17)?.tag === "Err") && ((__match_scrutinee_17)?.type === "Result")) {
      return false;
    }
    throw new Error("Non-exhaustive patterns at runtime");
  })();
};
const isWhitespace = (str_19) => {
  return (() => {
    const __match_scrutinee_20 = callInfectious(isWhitespaceCode, callInfectious(getCharCode, str_19));
    if (((__match_scrutinee_20)?.tag === "Ok") && ((__match_scrutinee_20)?.type === "Result")) {
      const result_21 = ((__match_scrutinee_20)._0);
      return result_21;
    }
    if (((__match_scrutinee_20)?.tag === "Err") && ((__match_scrutinee_20)?.type === "Result")) {
      return false;
    }
    throw new Error("Non-exhaustive patterns at runtime");
  })();
};
export { isDigit, isUppercase, isLowercase, isAlpha, isAlphaNumeric, isWhitespace, char0, char9, charA, charZ, chara, charz, charApostrophe, isDigitCode, isUppercaseCode, isLowercaseCode, isAlphaCode, isAlphaNumericCode, isWhitespaceCode, getCharCode };
