// Generated by Workman compiler (Raw Zig mode)
const std = @import("std");
pub fn build(b: *std.Build) void {
    return blk_15: {
        const target = b.graph.host;
        break :blk_15 blk_14: {
            const optimize = b.standardOptimizeOption(.{});
            break :blk_14 blk_13: {
                const raylib = b.addLibrary(.{ .linkage = .static, .name = "raylib", .root_module = b.createModule(.{ .target = target, .optimize = optimize, .link_libc = true }) });
                break :blk_13 blk_12: {
                    const raylib_sources = .{ "rcore.c", "rshapes.c", "rtextures.c", "rtext.c", "rmodels.c", "utils.c", "raudio.c", "rglfw.c" };
                    break :blk_12 blk_11: {
                        _ = raylib.root_module.addCSourceFiles(.{ .root = b.path("raylib-src/src"), .files = &raylib_sources, .flags = &.{"-DPLATFORM_DESKTOP_GLFW"} });
                        break :blk_11 blk_10: {
                            _ = raylib.root_module.addIncludePath(b.path("raylib-src/src"));
                            break :blk_10 blk_9: {
                                _ = raylib.root_module.addIncludePath(b.path("raylib-src/src/external/glfw/include"));
                                break :blk_9 blk_8: {
                                    _ = raylib.root_module.linkSystemLibrary("opengl32", .{});
                                    break :blk_8 blk_7: {
                                        _ = raylib.root_module.linkSystemLibrary("gdi32", .{});
                                        break :blk_7 blk_6: {
                                            _ = raylib.root_module.linkSystemLibrary("winmm", .{});
                                            break :blk_6 blk_5: {
                                                _ = raylib.root_module.linkSystemLibrary("user32", .{});
                                                break :blk_5 blk_4: {
                                                    _ = raylib.root_module.linkSystemLibrary("shell32", .{});
                                                    break :blk_4 blk_3: {
                                                        const exe = b.addExecutable(.{ .name = "raylibtest", .root_module = b.createModule(.{ .root_source_file = b.path("raylibtest.zig"), .target = target, .optimize = optimize }) });
                                                        break :blk_3 blk_2: {
                                                            _ = exe.root_module.addIncludePath(b.path("raylib-src/src"));
                                                            break :blk_2 blk_1: {
                                                                _ = exe.root_module.linkLibrary(raylib);
                                                                break :blk_1 blk_0: {
                                                                    _ = b.installArtifact(exe);
                                                                    break :blk_0 {};
                                                                };
                                                            };
                                                        };
                                                    };
                                                };
                                            };
                                        };
                                    };
                                };
                            };
                        };
                    };
                };
            };
        };
    };
}
